import type { Locale } from './locale';
const en = {
  skip: 'Skip to content',
  demo: 'Engineering demo',
  nav: 'How it works',
  open: 'Try the review queue',
  eyebrow: 'A little imagination. A considered system.',
  headline: 'Good ideas.',
  accent: 'Thoughtfully made.',
  intro:
    'A small creative workflow, from a first draft to a human decision. Explore it with sample content and nothing to set up.',
  secondary: 'Look under the hood',
  note: 'Synthetic content. No account. No publishing.',
  canvasLabel: 'Sample creative',
  sample: 'Fictional studio / 001',
  sampleHook: 'A little space\nfor a fresh start.',
  sampleFooter: 'MAKE ROOM FOR SOMETHING GOOD',
  ribbon: 'An idea, with a little structure.',
  ribbonText: 'Create. Check. Decide. Every step has a purpose.',
  section: 'THE WORKFLOW',
  sectionTitle: 'Follow a draft through three steps.',
  sectionIntro:
    'Explore three steps of a working demo. The repository explains the engineering behind each one.',
  steps: [
    {
      title: 'Start with a brief.',
      text: 'A small brief becomes a draft. The demo uses a predictable mock generator.',
    },
    {
      title: 'Give it a second look.',
      text: 'The judge response is simulated, with no quality assessment. Code checks completeness and supported formats.',
    },
    {
      title: 'Keep the final say.',
      text: 'Review a sample, approve it or pass. A repeated tap never spends another credit.',
    },
  ],
  bottomTitle: 'You decide which drafts to keep.',
  bottomText: 'Three sample creatives are waiting. Take the review flow for a spin.',
  footer: 'An independent rebuild of patterns from Ghost Creative. Demo code, synthetic data.',
  original: 'Visit Ghost Creative',
  language: 'Language',
  reviewEyebrow: 'THE REVIEW ROOM',
  reviewTitle: 'A fresh pair of eyes.',
  reviewIntro:
    'Choose what moves forward. Each approval uses one demo credit. Nothing is published.',
  back: 'Back to overview',
  credits: 'Demo credits',
  pending: 'To review',
  approved: 'Approved',
  rejected: 'Passed',
  approve: 'Approve',
  reject: 'Pass',
  saving: 'Saving…',
  loading: 'Loading samples…',
  retry: 'Try again',
  error: 'Could not confirm the change. Retry the same action to check its status.',
  loadError: 'The queue is unavailable. Please retry.',
  conflict: 'Queue refreshed. Check the current status.',
  saved: 'Decision saved.',
  reset: 'Reset demo',
  resetting: 'Resetting…',
  resetDone: 'Demo reset. All samples are ready again.',
  resetError: 'Reset not confirmed. Check the current queue before trying again.',
  shared:
    'Your browser has its own demo session. A restart or session eviction clears it; you can reset it here.',
  count: 'samples',
};
export type Copy = typeof en;
export const copy: Record<Locale, Copy> = {
  en,
  de: {
    skip: 'Zum Content',
    demo: 'Engineering-Demo',
    nav: 'So läuft es',
    open: 'Review testen',
    eyebrow: 'Etwas Fantasie. Ein durchdachtes System.',
    headline: 'Gute Ideen.',
    accent: 'Mit Bedacht gemacht.',
    intro:
      'Ein kleiner Creative-Workflow, vom ersten Entwurf bis zu deiner Entscheidung. Teste ihn mit Beispielen, ganz ohne Setup.',
    secondary: 'Technik entdecken',
    note: 'Beispieldaten. Kein Konto. Kein Posting.',
    canvasLabel: 'Beispiel-Creative',
    sample: 'Fiktives Studio / 001',
    sampleHook: 'Ein wenig Raum\nfür neue Ideen.',
    sampleFooter: 'PLATZ FÜR ETWAS GUTES',
    ribbon: 'Eine Idee mit etwas Struktur.',
    ribbonText: 'Erstellen. Prüfen. Entscheiden. Jeder Schritt zählt.',
    section: 'DER WORKFLOW',
    sectionTitle: 'Begleite einen Entwurf durch drei Schritte.',
    sectionIntro:
      'Teste drei Schritte einer laufenden Demo. Das Repository erklärt die Technik hinter jedem Schritt.',
    steps: [
      {
        title: 'Mit einem Brief starten.',
        text: 'Aus einem kurzen Brief wird ein Entwurf. Die Demo nutzt einen planbaren Mock-Generator.',
      },
      {
        title: 'Noch einmal hinsehen.',
        text: 'Die Judge-Antwort ist simuliert, ohne Qualitätsbewertung. Der Code prüft Vollständigkeit und erlaubte Formate.',
      },
      {
        title: 'Selbst entscheiden.',
        text: 'Creative prüfen, freigeben oder passen. Ein doppelter Tap kostet keinen weiteren Credit.',
      },
    ],
    bottomTitle: 'Du entscheidest, welche Entwürfe bleiben.',
    bottomText: 'Drei Beispiel-Creatives warten. Probier den Review aus.',
    footer: 'Muster aus Ghost Creative, unabhängig neu gebaut. Demo-Code, synthetische Daten.',
    original: 'Ghost Creative ansehen',
    language: 'Sprache',
    reviewEyebrow: 'DER REVIEW-RAUM',
    reviewTitle: 'Ein frischer Blick.',
    reviewIntro:
      'Du wählst aus. Jede Freigabe kostet einen Demo-Credit. Nichts wird veröffentlicht.',
    back: 'Zur Übersicht',
    credits: 'Demo-Credits',
    pending: 'Offen',
    approved: 'Freigegeben',
    rejected: 'Gepasst',
    approve: 'Freigeben',
    reject: 'Passen',
    saving: 'Sichern…',
    loading: 'Beispiele laden…',
    retry: 'Nochmal',
    error: 'Änderung nicht bestätigt. Wiederhole dieselbe Aktion, um den Status zu prüfen.',
    loadError: 'Review nicht verfügbar. Versuch es erneut.',
    conflict: 'Review aktualisiert. Prüfe den Status.',
    saved: 'Gespeichert.',
    reset: 'Demo-Reset',
    resetting: 'Zurücksetzen…',
    resetDone: 'Demo zurückgesetzt. Alle Beispiele sind bereit.',
    resetError: 'Reset nicht bestätigt. Prüfe den Review, bevor du es erneut versuchst.',
    shared:
      'Dein Browser hat eine eigene Demo. Neustart oder Session-Verdrängung löscht sie; du kannst sie hier zurücksetzen.',
    count: 'Beispiele',
  },
  es: {
    skip: 'Ir al contenido',
    demo: 'Demo de ingeniería',
    nav: 'Cómo funciona',
    open: 'Prueba la revisión',
    eyebrow: 'Un poco de imaginación. Un sistema pensado.',
    headline: 'Buenas ideas.',
    accent: 'Hechas con intención.',
    intro:
      'Un pequeño flujo creativo, del primer borrador a tu decisión. Explóralo con contenido de ejemplo y sin configurar nada.',
    secondary: 'Explora el proceso',
    note: 'Contenido ficticio. Sin cuenta. Sin publicaciones.',
    canvasLabel: 'Creative de ejemplo',
    sample: 'Estudio ficticio / 001',
    sampleHook: 'Un poco de espacio\npara algo nuevo.',
    sampleFooter: 'DALE ESPACIO A ALGO BUENO',
    ribbon: 'Una idea con un poco de estructura.',
    ribbonText: 'Crear. Revisar. Decidir. Cada paso tiene un propósito.',
    section: 'EL PROCESO',
    sectionTitle: 'Sigue un borrador a lo largo de tres pasos.',
    sectionIntro:
      'Explora tres pasos de una demo funcional. El repositorio explica la ingeniería detrás de cada uno.',
    steps: [
      {
        title: 'Empieza con un brief.',
        text: 'Un brief corto se convierte en un borrador. La demo usa un generador simulado y predecible.',
      },
      {
        title: 'Dale otra mirada.',
        text: 'La respuesta del evaluador es simulada y no evalúa la calidad. El código verifica que la respuesta esté completa y el formato esté permitido.',
      },
      {
        title: 'Tú decides al final.',
        text: 'Revisa un ejemplo, apruébalo o descártalo. Un toque repetido nunca gasta otro crédito.',
      },
    ],
    bottomTitle: 'Tú decides qué borradores conservar.',
    bottomText: 'Tres creatives de ejemplo te esperan. Prueba el flujo de revisión.',
    footer:
      'Patrones de Ghost Creative, reconstruidos de forma independiente. Código de demo, datos ficticios.',
    original: 'Visita Ghost Creative',
    language: 'Idioma',
    reviewEyebrow: 'LA SALA DE REVISIÓN',
    reviewTitle: 'Una mirada fresca.',
    reviewIntro: 'Elige qué sigue. Cada aprobación usa un crédito de demo. No se publica nada.',
    back: 'Volver al inicio',
    credits: 'Créditos de demo',
    pending: 'Por revisar',
    approved: 'Aprobado',
    rejected: 'Descartado',
    approve: 'Aprobar',
    reject: 'Descartar',
    saving: 'Guardando…',
    loading: 'Cargando ejemplos…',
    retry: 'Reintentar',
    error: 'No pudimos confirmar el cambio. Repite la misma acción para revisar su estado.',
    loadError: 'La revisión no está disponible. Inténtalo de nuevo.',
    conflict: 'Revisión actualizada. Checa el estado.',
    saved: 'Decisión guardada.',
    reset: 'Reiniciar demo',
    resetting: 'Reiniciando…',
    resetDone: 'Demo reiniciada. Todos los ejemplos están listos de nuevo.',
    resetError: 'No se confirmó el reinicio. Checa la revisión antes de intentarlo de nuevo.',
    shared:
      'Tu navegador tiene su propia demo. Se borra al reiniciar el servidor o al llegar al límite de sesiones; puedes reiniciarla aquí.',
    count: 'ejemplos',
  },
};
